version: 0.1
os: linux
files:
  - source: s3://heraj-first-s3-bucket-tesco/target/d98e959f-8f38-4c19-a85c-f5fbbd9230ee/FirstAWS/target
    destination: /var/www/html/WordPress
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/run_java_app.sh
      timeout: 300
      runas: root