version: 0.1
environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  pre_build:
    commands:
      - echo This is pre_build
  build:
    commands:
      - echo java `-version`
      - echo Starting build `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - buildspec.yml
    - target/first-vertx-app.jar
discard-paths: yes