version: 0.1
environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y maven
      - echo mvn version mvn --version
      - export M2=/usr/local/apache-maven/apache-maven-3.3.9
      - export PATH=$M2:$PATH
  pre_build:
    commands:
      - echo This is pre_build
  build:
    commands:
      - echo java `-version`
      - echo Starting build `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/first-vertx-app.jar
discard-paths: yes